name: docs
on:
    push:
        branches:
            - master
env:
    DOIT_NUM_PROCESS: 0
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repository
            uses: actions/checkout@v2
          - name: install ubuntu requirements
            env:
                DRAWIO_VERSION: '14.5.1'
            run: |
                sudo apt update
                wget https://github.com/jgraph/drawio-desktop/releases/download/v$DRAWIO_VERSION/drawio-amd64-$DRAWIO_VERSION.deb
                sudo apt install -q -y ./drawio-amd64-$DRAWIO_VERSION.deb
          - name: install python
            uses: actions/setup-python@v1
            with:
                python-version: "3.10"
          - name: install requirements.pip.dev.txt
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.pip.dev.txt
          - name: doit docs
            run: doit docs
          - name: create CNAME
            if: github.repository == 'hat-open/hat-stc'
            run: |
                 echo "hat-stc.hat-open.com" > build/docs/CNAME
          - name: deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build/docs
                publish_branch: gh-pages
                force_orphan: true
